[db_factory]
default_db_struct = "MariaDB"

[db_psql]
host = "localhost"
port = "5432"
db_name = "fmdp"
user = "postgres"
password = "postgres"

[db_sqlite]
db_name = "fmdp.db"

[db_mariadb]
host = "localhost"
port = "3306"
db_name = "fmdp"
user = "isaac"
password = "1234"
